name: Coverage Badge

on:
  push:
    branches:
      - main
      - multiple_dm

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.11
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run test coverage
        run: pytest --cov=src

      - name: Generate Coverage Badge
        run: coverage-badge -o coverage.svg

      - name: Commit Badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout $GITHUB_REF # Checkout the branch specified in GITHUB_REF
          git add coverage.svg -f
          git commit -m "Update coverage badge [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}