name: Coverage Badge

on:
  pull_request:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.11

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Delete old coverage badge
        run: rm coverage.svg

      - name: Run test coverage
        run: pytest --cov=src

      - name: Generate Coverage Badge
        run: coverage-badge -o coverage.svg

      - name: Commit and Push Badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout ${{ github.event.pull_request.head.ref }}
          git add coverage.svg -f
          git commit -m "Update coverage badge"
          git push origin ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}