name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3.1.2
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: |
          requirements_dev.txt
          setup.py

    - name: Install project dependencies
      run:
        python -m pip install --upgrade pip >>$GITHUB_OUTPUT
        pip install -r requirements_dev.txt >>$GITHUB_OUTPUT

    - name: Lint
      run: python -m flake8 src/tanks/ test/ setup.py >>$GITHUB_OUTPUT