name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.11' ]

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3.1.2
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: |
          dev-requirements.txt
          setup.py

    - name: Install project dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Lint
      run: flake8 src/tanks/ test/ setup.py