name: Tests

on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3.1.2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Venv
      run: |
        chmod +x ./setup_env.sh
        ./setup_env.sh
    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Print environment variables
      run: echo "TEST_DB_USER=$TEST_DB_USER, TEST_DB_PASSWORD=$TEST_DB_PASSWORD, TEST_DB_HOST=$TEST_DB_HOST, TEST_DB_PORT=$TEST_DB_PORT"
      env:
        TEST_DB_NAME: 'foobar'
        TEST_DB_USER: 'postgres'
        TEST_DB_PASSWORD: 'postgres'
        TEST_DB_PORT: '5432'
    - name: Tox test suite
      run: |
        set -x
        tox
      env:
        TEST_DB_NAME: 'foobar'
        TEST_DB_USER: 'postgres'
        TEST_DB_PASSWORD: 'postgres'
        TEST_DB_PORT: '5432'